version: '3.7'

services:
    mikro_app:
        build: .
        container_name: mikro_app
        volumes:
            - .:/app
            - ~/.composer:/.composer
        ports:
            -   8080:8080